import { createFileRoute } from "@tanstack/react-router";
import {
  AlertTriangle,
  CalendarCheck,
  CheckCircle2,
  Eraser,
  Gavel,
  ListChecks,
  Repeat,
  Sparkle,
} from "lucide-react";
import { useState, type ReactNode } from "react";

import { AiDisclaimer } from "@/components/ai-disclaimer";
import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { useAiFeature } from "@/lib/use-ai-feature";

export const Route = createFileRoute("/meetings")({
  head: () => ({
    meta: [
      { title: "Meeting Notes Summarizer — Aura Assist" },
      {
        name: "description",
        content:
          "Turn messy meeting notes into an executive summary, decisions, owners, deadlines, risks and follow-ups.",
      },
      { property: "og:title", content: "Meeting Notes Summarizer — Aura Assist" },
      {
        property: "og:description",
        content: "Decision-ready meeting records generated by AI.",
      },
    ],
  }),
  component: MeetingSummarizer,
});

type MeetingSummary = {
  executive_summary: string;
  key_points: string[];
  decisions: string[];
  action_items: { task: string; owner: string; deadline: string; priority: string }[];
  risks: string[];
  follow_ups: string[];
  sentiment: string;
};

function SectionCard({
  title,
  icon,
  children,
}: {
  title: string;
  icon: ReactNode;
  children: ReactNode;
}) {
  return (
    <Card className="glass-panel animate-rise transition-all duration-300 hover:-translate-y-0.5 hover:shadow-glow">
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2 text-base">
          <span className="grid h-8 w-8 place-items-center rounded-lg bg-primary/10 text-primary">
            {icon}
          </span>
          {title}
        </CardTitle>
      </CardHeader>
      <CardContent className="text-sm">{children}</CardContent>
    </Card>
  );
}

function BulletList({ items, empty }: { items: string[]; empty: string }) {
  if (items.length === 0) {
    return <p className="text-xs text-muted-foreground">{empty}</p>;
  }
  return (
    <ul className="space-y-2">
      {items.map((item) => (
        <li key={item} className="flex gap-2">
          <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" aria-hidden="true" />
          <span className="min-w-0">{item}</span>
        </li>
      ))}
    </ul>
  );
}

function MeetingSummarizer() {
  const [notes, setNotes] = useState("");
  const [touched, setTouched] = useState(false);
  const { result, isLoading, run, reset } = useAiFeature<MeetingSummary>("meeting");
  const invalid = notes.trim().length < 30;

  const summarize = () => {
    setTouched(true);
    if (invalid) return;
    void run({ notes });
  };

  return (
    <div className="space-y-6">
      <PageHeader
        icon={CalendarCheck}
        eyebrow="Meetings"
        title="Meeting Notes Summarizer"
        description="Paste raw notes and get a structured, decision-ready record."
      />

      <Card className="glass-panel animate-rise">
        <CardHeader>
          <CardTitle>Meeting notes</CardTitle>
          <CardDescription>
            Bullet fragments, transcripts or scribbles all work. Avoid sensitive personal data.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Label htmlFor="notes" className="sr-only">
            Meeting notes
          </Label>
          <Textarea
            id="notes"
            value={notes}
            onChange={(event) => setNotes(event.target.value)}
            rows={9}
            maxLength={16000}
            placeholder="Attendees, topics discussed, decisions, who agreed to do what and by when…"
            aria-invalid={touched && invalid}
            aria-describedby="notes-help"
          />
          <p
            id="notes-help"
            className={`text-xs ${touched && invalid ? "text-destructive" : "text-muted-foreground"}`}
          >
            {touched && invalid
              ? "Add at least a couple of sentences of notes to summarize."
              : `${notes.length}/16000 characters`}
          </p>
          <div className="flex flex-wrap gap-2">
            <Button onClick={summarize} disabled={isLoading} className="shadow-glow">
              <Sparkle className="h-4 w-4" aria-hidden="true" />
              {isLoading ? "Summarizing…" : "Summarize meeting"}
            </Button>
            <Button
              variant="ghost"
              disabled={isLoading}
              onClick={() => {
                setNotes("");
                setTouched(false);
                reset();
              }}
            >
              <Eraser className="h-4 w-4" aria-hidden="true" />
              Clear
            </Button>
          </div>
          <AiDisclaimer />
        </CardContent>
      </Card>

      {isLoading ? (
        <div className="grid gap-4 md:grid-cols-2" aria-live="polite">
          {[0, 1, 2, 3].map((index) => (
            <Card key={index} className="glass-panel">
              <CardHeader>
                <Skeleton className="h-5 w-40" />
              </CardHeader>
              <CardContent className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-10/12" />
                <Skeleton className="h-4 w-8/12" />
              </CardContent>
            </Card>
          ))}
        </div>
      ) : result ? (
        <div className="space-y-4">
          <SectionCard title="Executive summary" icon={<Sparkle className="h-4 w-4" />}>
            <p className="leading-relaxed">{result.executive_summary}</p>
            <Badge variant="secondary" className="mt-3">
              Tone: {result.sentiment}
            </Badge>
          </SectionCard>

          <div className="grid gap-4 md:grid-cols-2">
            <SectionCard title="Key discussion points" icon={<ListChecks className="h-4 w-4" />}>
              <BulletList items={result.key_points} empty="No discussion points detected." />
            </SectionCard>
            <SectionCard title="Decisions made" icon={<Gavel className="h-4 w-4" />}>
              <BulletList items={result.decisions} empty="No decisions were recorded." />
            </SectionCard>
          </div>

          <SectionCard title="Action items" icon={<CheckCircle2 className="h-4 w-4" />}>
            {result.action_items.length === 0 ? (
              <p className="text-xs text-muted-foreground">No commitments were captured.</p>
            ) : (
              <ul className="grid gap-3 sm:grid-cols-2">
                {result.action_items.map((item) => (
                  <li
                    key={`${item.task}-${item.owner}`}
                    className="rounded-xl border border-border/60 bg-card/50 p-3 transition-colors hover:border-primary/40"
                  >
                    <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-2">
                      <p className="min-w-0 font-semibold">{item.task}</p>
                      <Badge
                        variant="secondary"
                        className={
                          item.priority === "High"
                            ? "shrink-0 bg-destructive/15 text-destructive"
                            : item.priority === "Medium"
                              ? "shrink-0 bg-warning/20 text-foreground"
                              : "shrink-0 bg-success/15 text-success"
                        }
                      >
                        {item.priority}
                      </Badge>
                    </div>
                    <p className="mt-1 text-xs text-muted-foreground">
                      Owner: {item.owner} · Due: {item.deadline}
                    </p>
                  </li>
                ))}
              </ul>
            )}
          </SectionCard>

          <div className="grid gap-4 md:grid-cols-2">
            <SectionCard title="Risks" icon={<AlertTriangle className="h-4 w-4" />}>
              <BulletList items={result.risks} empty="No risks were raised." />
            </SectionCard>
            <SectionCard title="Follow-up tasks" icon={<Repeat className="h-4 w-4" />}>
              <BulletList items={result.follow_ups} empty="No follow-ups needed." />
            </SectionCard>
          </div>
        </div>
      ) : (
        <Card className="glass-panel">
          <CardContent className="py-12 text-center">
            <CalendarCheck
              className="mx-auto h-8 w-8 text-muted-foreground/60"
              aria-hidden="true"
            />
            <p className="mt-3 text-sm font-semibold">Nothing summarized yet</p>
            <p className="text-xs text-muted-foreground">
              Paste your notes above to generate a structured meeting record.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}