/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailRouteImport } from './routes/email'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/responsible-ai'
    | '/api/ai'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/responsible-ai'
    | '/api/ai'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/research'
    | '/responsible-ai'
    | '/api/ai'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailRoute: typeof EmailRoute
  MeetingsRoute: typeof MeetingsRoute
  PlannerRoute: typeof PlannerRoute
  ResearchRoute: typeof ResearchRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailRoute: EmailRoute,
  MeetingsRoute: MeetingsRoute,
  PlannerRoute: PlannerRoute,
  ResearchRoute: ResearchRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
  ApiAiRoute: ApiAiRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
